version: '3'

services:
  orders-db:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth-db
    container_name: auth-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
